name: cdlib
dependencies:
- python>=3.8
- numpy
- matplotlib
- scikit-learn
- tqdm
- networkx>=2.4
- demon
- python-louvain
- nf1
- scipy
- pulp
- seaborn
- pandas
- eva_lcd
- karateclub
- bimlpa
- markov_clustering
- chinese_whispers
- python-igraph
- leidenalg
- angel_cd
- pooch
- dynetx
- python-infomap
- wurlitzer
- thresholdclustering
- pyclustering
- python-Levenshtein
- graph-tool
